### ISSUE TITLE
Add inference code for simulated data

### ISSUE THREAD

**Issue by sdwfrost** [msylau/A-mechanistic-spatio-temporal-framework-for-modelling-individual-to-individual-transmission-Ebola#1]
Dear @msylau 

Is it possible to add in the code for the inference? I understand you can't share the real data, but an example on the simulated data would be great.

**Comment by msylau** [comment]
Dear @sdwfrost ,

Thanks for your interest. Will upload that soon.

**Comment by msylau** [comment]
Dear @sdwfrost , 

Inference code uploaded. It is in C++ with minimal instructions but happy to answer questions.

**Comment by sdwfrost** [comment]
Thanks! That's great. Would it be OK if I shared a modified copy of the simulation model on @epirecipes?

**Comment by msylau** [comment]
Hi, do you have a little more info on epirecipes?

**Comment by sdwfrost** [comment]
Yes, it's an online repository of epidemiological models, as a set of Jupyter notebooks. The idea is to be interactive, and to have examples of lots of models, in lots of languages. The main website is [http://epirecip.es/](http://epirecip.es/) and the 'cookbook' itself is [here](http://epirecip.es/epicookbook/chapters/simple).

**Comment by msylau** [comment]
This sounds great. Feel free to share the code as long as our paper and code are properly cited.
